### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by omajid**
This drops support for python2, though.

Python 2 was EOL'ed on Jan 2020, so I am not sure supporting it going foward makes any sense. Let me know if you would like to keep support for it, though.

### CODE REVIEW

**Comment by omajid** [comment]
This contribution is under a Free/Libre/Open Source license ("CC0/Public Domain/MIT"  to quote @thomasf)... even though the license of this project itself is unknown: https://github.com/thomasf/exitwp/issues/55

Do you intend to maintain this code longer term? Would you be open to enabling the issues tab in github?

**Comment by wooni005** [comment]
Sorry for the late response, but thank you Omair for the Python3 port. This was still on my todo list, but you did it ;-).
Currently I don't have the time to test this Python3 port, did you test it well? Can I merge the pull request without breaking the functionality?

We also need to update the install documentation. For sure the pip_requirements.txt needs to be updated.

Nice that the port to Python3 is ready!

**Comment by omajid** [comment]
> Sorry for the late response, but thank you Omair for the Python3 port. This was still on my todo list, but you did it ;-).

No worries. Happy to scratch my own itch.

> Currently I don't have the time to test this Python3 port, did you test it well? Can I merge the pull request without breaking the functionality?

No, I haven't tested it extensively in any way. I used it to perform a test migration of my wordpress blog. That worked. It's a trivial 100% text blog, so I doubt I hit most of the strange corner cases.

> We also need to update the install documentation. For sure the pip_requirements.txt needs to be updated.

Okay, but I am quite hesitant to touch this code again given that the code is effectively proprietary because there's on license attached: https://choosealicense.com/no-permission/

**Comment by wooni005** [comment]
Thanks for the choosealicense.com link, good point. Never looked in that perspective ;-). I've added the GNU GPLv3 license, that suits me well.

**Comment by wooni005** [comment]
Also added the Issues tab!

**Comment by thomasf** [comment]
IIRC there were contributions taken before that one (you have to check the commit history) so probably still undefined.

**Comment by thomasf** [comment]
These two github users made code changes before the html parser were added:

- bascht
- jimjimovich

These people has only changed the readme slightly, maybe you should ask them anyway.

- juliangruber
- etc

I you try to contact them and ask for a gplv3 grant you should be fine.

**Pull request closed without merging**
